---

service: serverless-layer-custom-ca
frameworkVersion: ">2.0.0"

provider:
  name: aws
  lambdaHashingVersion: 20201221

  environment:
    REQUESTS_CA_BUNDLE: python/cacert.pem
    SSL_CERT_FILE: python/cacert.pem
    NODE_EXTRA_CA_CERTS: nodejs/node_modules/cacert.pem   

  layers:
    - { Ref: CustomCALambdaLayer }

package:
  patterns:
    - layer
    - lambda_function.py
    - lambda_function.js

layers:
  customCA:
    path: layer
    description: A Layer to add my custom CA

    compatibleRuntimes:
      - python3.6
      - nodejs14.x

functions:
  testPython:
    handler: lambda_function.lambda_handler
    runtime: python3.6

  testNode:
    handler: lambda_function.lambda_handler
    runtime: nodejs14.x
